sudo: required
dist: trusty
group: edge

language: java
cache:
  directories: $HOME/.gradle
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
before_install: pip install --user codecov
before_script: # init GUI for tests that can't run headless
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: ./.travis/script

# Release the plugin via GitHub releases when pushing a tag
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file:
    - "build/libs/Mapillary.jar"
    - "build/tmp/jar/MANIFEST.MF"
  skip_cleanup: true
  on:
    tags: true

# Deploy to GitHub pages
after_script: ./.travis/after_script

after_success: codecov

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk9
