name: Release

on:
  release:
    types: [created]

jobs:
  call-workflow:
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v2
    with:
      josm-revision: "r18877"
      java-version: 17
  add-mapillary-keys:
    runs-on: ubuntu
    needs: call-workflow
    steps:
      - name: Get Mapillary jar
        run: gh release download ${{ github.ref_name }} --pattern Mapillary.jar
      - name: Add keys
        run: |
            cat <<EOF > mapillary_api_keys.json
            {
                "MAPILLARY_CLIENT_ID": "${real_MAPILLARY_CLIENT_ID}",
                "MAPILLARY_CLIENT_TOKEN": "${real_MAPILLARY_CLIENT_TOKEN}",
                "MAPILLARY_CLIENT_SECRET": "${real_MAPILLARY_CLIENT_SECRET}"
            }
            EOF
            zip Mapillary.jar mapillary_api_keys.json
      - name: Upload Mapillary jar
        run: gh release upload ${{ github.ref_name }} --clobber Mapillary.jar
