name: Java CI

on:
  push:
    branches:
      - master
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - master
      - $default-branch
  workflow_dispatch:

jobs:
  call-workflow-latest:
      uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v2
      with:
          josm-revision: ""
          java-version: 17
  call-workflow-min:
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v2
    with:
      josm-revision: "r18877"
      java-version: 17
      perform-revision-tagging: ${{ github.repository == 'JOSM/Mapillary' && github.ref_type == 'branch' && github.ref_name == 'master' && github.event_name != 'schedule' && github.event_name != 'pull_request' }}

  add-mapillary-keys:
      runs-on: ubuntu
      needs: call-workflow-min
      if: needs.call-workflow-min.outputs.tag
      steps:
          - name: Get Mapillary jar
            run: gh release download ${{ needs.call-workflow-min.outputs.tag }} --pattern Mapillary.jar
          - name: Add keys
            run: |
                cat <<EOF > mapillary_api_keys.json
                {
                    "MAPILLARY_CLIENT_ID": "${real_MAPILLARY_CLIENT_ID}",
                    "MAPILLARY_CLIENT_TOKEN": "${real_MAPILLARY_CLIENT_TOKEN}",
                    "MAPILLARY_CLIENT_SECRET": "${real_MAPILLARY_CLIENT_SECRET}"
                }
                EOF
                zip Mapillary.jar mapillary_api_keys.json
          - name: Upload Mapillary jar
            run: gh release upload ${{ needs.call-workflow-min.outputs.tag }} --clobber Mapillary.jar
